**Reading order**

**Pick a Random number in python**

In the following task, you will be asked to apply x-gate to randomly picked quantum bits.

Here is one of the methods to pick a random number in python.

In [ ]:
from random import randrange
n = 20
r=randrange(n) # pick a number from the list {0,1,...,n-1}
print(r)

# test this method by using a loop
for i in range(10):
    print(randrange(n))

**Task 2**

Design a quantum circuit with 8 quantum bits and 8 classical bits.

For each quantum bit, flip a coin by python, and apply x-gate if the outcome is head.

Measure your quantum bits.

Execute your circuit 10 times.

Repeat this task as much as you want, and enjoy your random choices.

In [ ]:
#
#your solution is here

**Pennylane Refferences**

In [ ]:
import pennylane as qml
from pennylane import numpy as np


**Creating a quantum circuit**

In [ ]:
import pennylane as qml
from pennylane import numpy as np

# Define a quantum device with 5 wires (qubits)
dev = qml.device("default.qubit", wires=5)

# If you want a 3-qubit device instead
# dev = qml.device("default.qubit", wires=3)



**One qubit gates**

x-gate (NOT operator)

In [ ]:
import pennylane as qml

# Define a device with 5 qubits
dev = qml.device("default.qubit", wires=5)

@qml.qnode(dev)
def circuit():
    qml.PauliX(wires=2)  # Apply X-gate to qubit 2
    return qml.state()


z-gate(Z operator)

In [ ]:
import pennylane as qml

dev = qml.device("default.qubit", wires=5)

@qml.qnode(dev)
def circuit():
    qml.PauliZ(wires=4)  # Apply Z gate to qubit 4
    return qml.state()


  h-gate (Hadamard operator)

In [ ]:
import pennylane as qml

dev = qml.device("default.qubit", wires=2)

@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=1)  # Apply Hadamard to qubit 1
    return qml.state()


  ry-gate (rotation operator)

This is a rotation operator on a (real-valued) qubit in counter-clockwise direction.

In [ ]:
import pennylane as qml
from math import pi

dev = qml.device("default.qubit", wires=4)

@qml.qnode(dev)
def circuit():
    a = pi / 7
    qml.RY(2 * a, wires=3)
    return qml.state()


 **Two-qubit gates**

In [ ]:
 cx-gate (CNOT operator)

In [6]:
!pip install -q pennylane


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.1/57.1 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 51.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.8/930.8 kB 44.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 49.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 67.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 85.0 MB/s eta 0:00:00


In [8]:
import pennylane as qml
from math import pi
a = pi / 7
dev = qml.device("default.qubit", wires=2)

@qml.qnode(dev)
def circuit():
    # Apply controlled-U3 (equivalent to CU3 in Qiskit)
    qml.ctrl(qml.Rot, control=1)(2 * a, 0, 0, wires=0)
    return qml.state()



**Three-qubit gate**

In [9]:
import pennylane as qml

dev = qml.device("default.qubit", wires=3)

@qml.qnode(dev)
def circuit():
    # Apply Toffoli gate (CCX) with control wires 2 and 1, and target wire 0
    qml.Toffoli(wires=[2, 1, 0])
    return qml.state()



**Measuring a quantum circuit**

In PennyLane, you don’t have a separate “classical register” like in Qiskit. Instead, you simply measure quantum wires, and PennyLane returns their outcomes.

1. Measuring specific wires and returning samples:

In [ ]:
import pennylane as qml

dev = qml.device("default.qubit", wires=5, shots=1000)

@qml.qnode(dev)
def circuit():
    # Add gates here (e.g., qml.X(wires=0)) if needed

    return qml.sample(wires=[0, 3, 1, 4, 2])  # Equivalent to qc.measure(q[0],c[3]), etc.


2. Default one-to-one mapping

In [ ]:
@qml.qnode(dev)
def circuit():
    return qml.sample(wires=range(5))  # wires 0 to 4


3. Partial measurement

In [ ]:
@qml.qnode(dev)
def circuit():
    return qml.sample(wires=[2, 3, 4])


**Emulate Conditional X Gate After Measurement**

---



import pennylane as qml
from pennylane import numpy as np

# Set up device with 1 qubit and 1 shot for classical behavior
dev = qml.device("default.qubit", wires=1, shots=1)

# Step 1: measure the qubit
@qml.qnode(dev)
def measure_qubit():
    qml.Hadamard(wires=0)
    return qml.sample(wires=0)  # classical 0 or 1

# Step 2: conditional X gate based on measured result
@qml.qnode(dev)
def apply_x_if_needed():
    qml.PauliX(wires=0)
    return qml.state()

@qml.qnode(dev)
def skip_x():
    return qml.state()

# Execute the logic
measurement_result = measure_qubit()[0]  # extract the single-shot result
print("Measured:", measurement_result)

# Apply conditional operation
if measurement_result == 1:
    final_state = apply_x_if_needed()
else:
    final_state = skip_x()

print("Final state:", final_state)


 **Drawing or printing a quantum circuit**

In [ ]:
!pip -q install pennylane
import pennylane as qml
from math import pi

dev = qml.device("default.qubit", wires=4)

@qml.qnode(dev)
def circuit():
    qml.X(3)
    qml.Hadamard(0)
    return qml.state()

# Draw ASCII diagram
print(qml.draw(circuit)())

# For visual drawing (if matplotlib plugin is set up)
# qml.drawer.draw_mpl(circuit)()


0: ──H─┤  State
3: ──X─┤  State


**Executing a quantum program on local simulator**

 Executing a quantum program 1000 times:

In [ ]:
import pennylane as qml
from collections import Counter
import numpy as np

dev = qml.device("default.qubit", wires=4, shots=1000)

@qml.qnode(dev)
def circuit():
    # Build your circuit here (e.g., qml.Hadamard(wires=0), qml.CNOT(wires=[0,1]), etc.)
    return qml.sample(wires=[0, 1, 2, 3])  # sample from all 4 wires

# Execute circuit and count measurement results
samples = circuit()  # shape: (shots, wires)
bitstrings = ["".join(str(bit) for bit in sample) for sample in samples]
counts = Counter(bitstrings)

print(counts)


Counter({'0000': 1000})


The results can be accessed as a dictionary:

In [ ]:
from collections import Counter

samples = circuit()  # run your PennyLane QNode to get samples
bitstrings = ["".join(map(str, sample)) for sample in samples]
counts = Counter(bitstrings)

print(counts)


Counter({'0000': 1000})


**Reading the quantum state of a circuit on local simulator**

The quantum state of a circuit can be read when using "StatevectorSimulator".

In [ ]:
import pennylane as qml
from math import pi
import numpy as np

dev = qml.device("default.qubit", wires=4)  # specify number of qubits explicitly

@qml.qnode(dev)
def circuit():
    # example gates, replace with your circuit
    qml.PauliX(wires=0)
    qml.Hadamard(wires=1)
    qml.RY(2 * pi / 7, wires=3)
    return qml.state()

state = circuit()
precision = 3
state_rounded = np.round(state, precision)
print(state_rounded)


[0.   +0.j 0.   +0.j 0.   +0.j 0.   +0.j 0.   +0.j 0.   +0.j 0.   +0.j
 0.   +0.j 0.637+0.j 0.307+0.j 0.   +0.j 0.   +0.j 0.637+0.j 0.307+0.j
 0.   +0.j 0.   +0.j]


The result is a list of complex numbers. We can access the amplitude of each state by using its index, e.g.,

In [ ]:
state = circuit()  # output of qml.state(), a complex numpy array

# real part of the first amplitude
real_part = state[0].real

# imaginary part of the first amplitude
imag_part = state[0].imag

print("Real part:", real_part)
print("Imaginary part:", imag_part)


Real part: 0.0
Imaginary part: 0.0


**Reading the unitary operator of a circuit on local simulator**

"UnitarySimulator" gives a unitary representation of all gates in the circuit until that point

In [ ]:
import pennylane as qml

# Suppose your circuit has 5 qubits (adjust wires accordingly)
dev = qml.device("default.qubit", wires=5)

@qml.qnode(dev)
def circuit():
    # apply your gates here, e.g.
    # qml.PauliX(wires=0)
    # qml.PauliX(wires=3)
    return qml.state()  # or qml.unitary() - see below

# To get the unitary matrix of the circuit, you use `qml.matrix`
unitary_matrix = qml.matrix(circuit)()

print(unitary_matrix.round(3))  # round for precision as in your code


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


The result is a double list of complex numbers (as it is a matrix).

In [ ]:
real_part = unitary_matrix[0, 0].real
imag_part = unitary_matrix[0, 0].imag

print("Real part:", real_part)
print("Imag part:", imag_part)


Real part: 1.0
Imag part: 0.0
